name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'
        run: echo "${{ secrets.ENV_PROD }}" >> .env.production
      - name: Build the Docker image
        run: |
          # IMAGE_TAG=hmt1/twitter:v$(date +%s)
          IMAGE_TAG=hmt1/freshfit-mail-media-service:latest
          docker build --progress=plain -t $IMAGE_TAG -f ./Dockerfile .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Print Image Tag
        run: echo ${{ env.IMAGE_TAG }}

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Image to Docker Hub
        run: docker push ${{ env.IMAGE_TAG }}

  deploy_VPS:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD  }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull hmt1/freshfit-mail-media-service:latest
            docker stop freshfit-mail-media-service
            docker rm freshfit-mail-media-service
            docker run -dp 4000:8085 --name freshfit-mail-media-service --restart unless-stopped  hmt1/freshfit-mail-media-service:latest
